Binance {
  apiKey = ${?BINANCE_API_KEY}
  url = "https://data-api.binance.vision/api/v3/"
}

Beaconcha {
  apiKey = ${?BEACONCHA_API_KEY}
  url = "https://gnosischa.in/api/v1"
}

Blockscout {
  apiKey = ${?BLOSCKOUT_API_KEY}
  url = "https://gnosis.blockscout.com/api/v2"
}

CowSwap {
  apiKey = "your-cowswap-api-key"
  url = "https://api.cow.fi/xdai"
}

Discord {
  gatewayUrl = "wss://gateway.discord.gg"
  apiUrl = "https://discord.com/api/v10"
  botToken = "bottoken"
}

GnosisScan {
  apiKey = ${?GNOSIS_SCAN_API_KEY}
  url = "https://api.gnosisscan.io/api"
}

Kafka {
  bootstrapServers = "localhost:9094"
  topic = "ethereum-logs"
  groupId = "scala-consumer"
}

Slack {
  webhook = ${?SLACK_WEBHOOK}
}

Server {
  # The port to listen on.
  port = 9999
  port = ${?PORT}
}

Grpc {
  host = "localhost"
  port = 50051
}

Validators {
  indices = ${?VALIDATORS_INDICES}
}