Beaconcha {
  apiKey = ${?BEACONCHA_API_KEY}
  url = "https://gnosischa.in/api/v1"
}

Blockscout {
  apiKey = ${?BLOSCKOUT_API_KEY}
  url = "https://gnosis.blockscout.com/api/v2"
}

GnosisScan {
  apiKey = ${?GNOSIS_SCAN_API_KEY}
  url = "https://api.gnosisscan.io/api"
}

Kafka {
  bootstrapServers = "localhost:9094"
  topic = "ethereum-logs"
  groupId = "scala-consumer"
}

Slack {
  webhook = ${?SLACK_WEBHOOK}
}

Server {
  # The port to listen on.
  port = 9999
  port = ${?PORT}
}

Grpc {
  host = "localhost"
  port = 50051
}

Validators {
  indices = ${?VALIDATORS_INDICES}
}